apiVersion: v2
name: onecx-product-store-ui
version: 0.0.0
description: OneCX Product Store UI
home: https://github.com/onecx/onecx-product-store-ui
keywords:
  - product-store
sources:
  - https://github.com/onecx/onecx-product-store-ui
maintainers:
  - name: OneCX Developer Team
    email: tkit_dev@1000kit.org
dependencies:
  - name: helm-angular-app
    version: 0.21.0
    repository: oci://ghcr.io/onecx/charts
    alias: app
